export interface CardOption {
  card_id: string;
  name: string;
  issuer: string;
  annual_fee: number;
}

export const CARD_OPTIONS: CardOption[] = [
  { card_id: "amex-bce", name: "Blue Cash Everyday® Card", issuer: "American Express", annual_fee: 0 },
  { card_id: "amex-bcp", name: "Blue Cash Preferred® Card", issuer: "American Express", annual_fee: 95 },
  { card_id: "amex-blue-business-cash", name: "The American Express Blue Business Cash™ Card", issuer: "American Express", annual_fee: 0 },
  { card_id: "amex-business-gold", name: "American Express Business Gold Card", issuer: "American Express", annual_fee: 375 },
  { card_id: "amex-delta-gold", name: "Delta SkyMiles® Gold American Express Card", issuer: "American Express", annual_fee: 150 },
  { card_id: "amex-delta-platinum", name: "Delta SkyMiles® Platinum American Express Card", issuer: "American Express", annual_fee: 350 },
  { card_id: "amex-delta-reserve", name: "Delta SkyMiles® Reserve American Express Card", issuer: "American Express", annual_fee: 650 },
  { card_id: "amex-everyday-preferred", name: "Amex EveryDay Preferred Credit Card", issuer: "American Express", annual_fee: 95 },
  { card_id: "amex-gold", name: "American Express® Gold Card", issuer: "American Express", annual_fee: 325 },
  { card_id: "amex-green", name: "American Express® Green Card", issuer: "American Express", annual_fee: 150 },
  { card_id: "amex-hilton-aspire", name: "Hilton Honors American Express Aspire Card", issuer: "American Express", annual_fee: 550 },
  { card_id: "amex-hilton-honors", name: "Hilton Honors American Express Card", issuer: "American Express", annual_fee: 0 },
  { card_id: "amex-hilton-honors-business", name: "Hilton Honors American Express Business Card", issuer: "American Express", annual_fee: 195 },
  { card_id: "amex-hilton-surpass", name: "Hilton Honors American Express Surpass Card", issuer: "American Express", annual_fee: 150 },
  { card_id: "amex-marriott-bonvoy-amex", name: "Marriott Bonvoy American Express Card", issuer: "American Express", annual_fee: 250 },
  { card_id: "amex-marriott-brilliant", name: "Marriott Bonvoy Brilliant® American Express® Card", issuer: "American Express", annual_fee: 650 },
  { card_id: "amex-platinum", name: "The Platinum Card® from American Express", issuer: "American Express", annual_fee: 895 },
  { card_id: "apple-card", name: "Apple Card", issuer: "Goldman Sachs", annual_fee: 0 },
  { card_id: "bilt-blue", name: "Bilt Blue Card", issuer: "First Electronic Bank", annual_fee: 0 },
  { card_id: "bilt-obsidian", name: "Bilt Obsidian Card", issuer: "First Electronic Bank", annual_fee: 95 },
  { card_id: "bilt-palladium", name: "Bilt Palladium Card", issuer: "First Electronic Bank", annual_fee: 495 },
  { card_id: "boa-alaska-ascent", name: "Alaska Airlines Atmos™ Ascent Visa Signature® Card", issuer: "Bank of America", annual_fee: 95 },
  { card_id: "boa-alaska-summit", name: "Alaska Airlines Atmos™ Summit Visa Infinite® Card", issuer: "Bank of America", annual_fee: 395 },
  { card_id: "boa-customized-cash-rewards", name: "Bank of America® Customized Cash Rewards Credit Card", issuer: "Bank of America", annual_fee: 0 },
  { card_id: "boa-travel-rewards", name: "Bank of America® Travel Rewards Credit Card", issuer: "Bank of America", annual_fee: 0 },
  { card_id: "capital-one-quicksilver", name: "Capital One Quicksilver Cash Rewards Credit Card", issuer: "Capital One", annual_fee: 0 },
  { card_id: "capital-one-savor", name: "Capital One Savor Rewards Credit Card", issuer: "Capital One", annual_fee: 0 },
  { card_id: "capital-one-savorone", name: "Capital One SavorOne Cash Rewards Credit Card", issuer: "Capital One", annual_fee: 39 },
  { card_id: "capital-one-spark-miles", name: "Capital One Spark Miles for Business", issuer: "Capital One", annual_fee: 95 },
  { card_id: "capital-one-venture", name: "Capital One Venture Rewards Credit Card", issuer: "Capital One", annual_fee: 95 },
  { card_id: "capital-one-venture-x", name: "Capital One Venture X Rewards Credit Card", issuer: "Capital One", annual_fee: 395 },
  { card_id: "chase-disney-inspire", name: "Disney Inspire Visa Card", issuer: "Chase", annual_fee: 149 },
  { card_id: "chase-freedom-flex", name: "Chase Freedom Flex®", issuer: "Chase", annual_fee: 0 },
  { card_id: "chase-freedom-rise", name: "Chase Freedom Rise Credit Card", issuer: "Chase", annual_fee: 0 },
  { card_id: "chase-freedom-unlimited", name: "Chase Freedom Unlimited®", issuer: "Chase", annual_fee: 0 },
  { card_id: "chase-ihg-premier", name: "IHG One Rewards Premier Credit Card", issuer: "Chase", annual_fee: 99 },
  { card_id: "chase-ink-business-cash", name: "Chase Ink Business Cash® Credit Card", issuer: "Chase", annual_fee: 0 },
  { card_id: "chase-ink-business-preferred", name: "Chase Ink Business Preferred® Credit Card", issuer: "Chase", annual_fee: 95 },
  { card_id: "chase-ink-business-unlimited", name: "Chase Ink Business Unlimited® Credit Card", issuer: "Chase", annual_fee: 0 },
  { card_id: "chase-marriott-boundless", name: "Marriott Bonvoy Boundless® Credit Card", issuer: "Chase", annual_fee: 95 },
  { card_id: "chase-sapphire-preferred", name: "Chase Sapphire Preferred® Card", issuer: "Chase", annual_fee: 95 },
  { card_id: "chase-sapphire-reserve", name: "Chase Sapphire Reserve®", issuer: "Chase", annual_fee: 795 },
  { card_id: "chase-united-explorer", name: "United℠ Explorer Card", issuer: "Chase", annual_fee: 150 },
  { card_id: "chase-united-quest", name: "United Quest Card", issuer: "Chase", annual_fee: 350 },
  { card_id: "citi-costco-anywhere", name: "Costco Anywhere Visa® Card by Citi", issuer: "Citi", annual_fee: 0 },
  { card_id: "citi-custom-cash", name: "Citi Custom Cash® Card", issuer: "Citi", annual_fee: 0 },
  { card_id: "citi-double-cash", name: "Citi Double Cash® Card", issuer: "Citi", annual_fee: 0 },
  { card_id: "citi-premier", name: "Citi Strata Premier® Card", issuer: "Citi", annual_fee: 95 },
  { card_id: "citi-strata-elite", name: "Citi Strata Elite℠ Card", issuer: "Citi", annual_fee: 595 },
  { card_id: "citi-strata-premier", name: "Citi Strata Premier℠ Card", issuer: "Citi", annual_fee: 95 },
  { card_id: "coinbase-one", name: "Coinbase One Card", issuer: "First Electronic Bank", annual_fee: 0 },
  { card_id: "discover-it", name: "Discover it® Cash Back", issuer: "Discover", annual_fee: 0 },
  { card_id: "discover-it-miles", name: "Discover it® Miles", issuer: "Discover", annual_fee: 0 },
  { card_id: "fidelity-rewards", name: "Fidelity Rewards Visa", issuer: "Fidelity", annual_fee: 0 },
  { card_id: "usbank-altitude-connect", name: "U.S. Bank Altitude® Connect Visa Signature® Card", issuer: "U.S. Bank", annual_fee: 0 },
  { card_id: "usbank-altitude-reserve", name: "U.S. Bank Altitude® Reserve Visa Infinite® Card", issuer: "U.S. Bank", annual_fee: 400 },
];
