/**
 * Creates a GitHub PR for a card update using the gh CLI.
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, unlinkSync } from "node:fs";
import path from "path";
import type { Card } from "./cards-loader";
import type { DiffResult } from "./diff";
import type { ExtractedData } from "./extract";
import type { RiskLevel } from "./config";
import { CONFIG } from "./config";

const DATE = new Date().toISOString().split("T")[0].replace(/-/g, "");

export async function createPR(
  card: Card,
  diff: DiffResult,
  extracted: ExtractedData,
  risk: RiskLevel
): Promise<string> {
  const branchName = `${CONFIG.BOT_BRANCH_PREFIX}-${card.card_id}-${DATE}`;

  // Check if PR already exists for this card today
  try {
    const existing = execSync(
      `gh pr list --author "github-actions[bot]" --state open --json number,title,headRefName --jq '.[] | select(.headRefName | startswith("bot/update-${card.card_id}-"))' 2>/dev/null`,
      { encoding: "utf8" }
    );
    if (existing.trim()) {
      console.log(`   ℹ️  PR already exists for ${card.card_id}, skipping`);
      return "";
    }
  } catch {
    // No existing PR
  }

  // Build PR title
  const changeSummary = diff.changes
    .map((c) => {
      const from = truncate(String(c.from ?? ""), 20);
      const to = truncate(String(c.to ?? ""), 20);
      return `${c.field}: ${from} → ${to}`;
    })
    .join("; ");

  const shortSummary = changeSummary.length > 80
    ? changeSummary.slice(0, 80) + "…"
    : changeSummary;

  const title = `[${risk}] update ${card.name}: ${shortSummary}`;

  // Build PR body
  const diffTable = diff.changes
    .map((c) => `| ${c.field} | \`${c.from ?? "null"}\` | \`${c.to ?? "null"}\` |`)
    .join("\n");

  const body = `## OpenCard Auto-Update

**Card:** ${card.name} (\`${card.card_id}\`)
**Risk:** ${risk}
**Confidence:** ${(extracted.confidence * 100).toFixed(0)}%

### Changes

| Field | Before | After |
|-------|--------|-------|
${diffTable}

### Source

${extracted.source_quote ? `> ${extracted.source_quote}\n\n` : ""}
Source: ${diff.source_url || "N/A"}

### Reviewer Checklist

- [ ] Verify the source URL is still an active offer
- [ ] Confirm AI extraction is accurate (check source_quote)
- [ ] Check if the change aligns with known updates (DoC/TPG/NerdWallet)

---
*Auto-generated by OpenCard bot · ${new Date().toISOString()}*`;

  // Write the PR body to a temp file (avoids shell escaping issues)
  const tmpDir = path.join(process.cwd(), "tmp");
  mkdirSync(tmpDir, { recursive: true });
  const bodyFile = path.join(tmpDir, `pr-body-${card.card_id}.txt`);
  writeFileSync(bodyFile, body);

  // Create branch
  try {
    execSync(`git checkout -b ${branchName} 2>/dev/null`, { cwd: process.cwd() });
  } catch {
    // Branch exists, just switch
    try {
      execSync(`git checkout ${branchName} 2>/dev/null`, { cwd: process.cwd() });
    } catch {
      // Already on this branch
    }
  }

  // Write the updated card JSON
  const cardPath = path.join(process.cwd(), "data/cards", `${card.card_id}.json`);
  const cardData = JSON.parse(readFileSync(cardPath, "utf8"));

  // Apply changes to card. When a change targets a nested field whose parent
  // doesn't exist (e.g. `welcome_offer.spending_requirement` on a card whose
  // `welcome_offer` is currently null), init missing ancestors as plain
  // objects so the assignment doesn't crash. 2026-05-05 apply run hit this
  // on capital-one-savorone.
  for (const change of diff.changes) {
    const parts = change.field.split(".");
    let obj: Record<string, unknown> = cardData;
    for (let i = 0; i < parts.length - 1; i++) {
      const key = parts[i];
      if (obj[key] == null) {
        obj[key] = {};
      }
      obj = obj[key] as Record<string, unknown>;
    }
    obj[parts[parts.length - 1]] = change.to;
  }
  cardData.last_updated = new Date().toISOString();

  writeFileSync(cardPath, JSON.stringify(cardData, null, 2));

  // Commit
  execSync(`git add data/cards/${card.card_id}.json`, { cwd: process.cwd() });
  execSync(`git commit -m "${title}"`, { cwd: process.cwd() });

  // Push
  execSync(`git push -u origin ${branchName} 2>&1`, { cwd: process.cwd() });

  // Create PR. Capture stderr explicitly: `execSync` only puts the command
  // string in `error.message` and stashes the merged stdout+stderr in
  // `error.stdout` — silent failures (label-not-found, permissions) lose
  // their explanation when callers only print `error.message`. Re-throw
  // with the captured output so the loop's logger surfaces the real cause.
  let prUrl: string;
  try {
    prUrl = execSync(
      `gh pr create --title "${title}" --body-file "${bodyFile}" --label "${CONFIG.RISK_LABELS[risk]}" --label "bot-generated" --label "needs-review" 2>&1`,
      { cwd: process.cwd(), encoding: "utf8" }
    ).trim();
  } catch (err) {
    const e = err as { stdout?: string | Buffer; stderr?: string | Buffer; message: string };
    const out = (e.stdout || "").toString().trim();
    const errOut = (e.stderr || "").toString().trim();
    throw new Error(`gh pr create failed: ${out || errOut || e.message}`);
  }

  // Clean up
  unlinkSync(bodyFile);

  console.log(`   ✅ Opened PR: ${prUrl}`);
  return prUrl;
}

function truncate(str: string, max: number): string {
  return str.length > max ? str.slice(0, max) + "…" : str;
}
